# Generated by Django 4.0.2 on 2023-09-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpipelineconfig',
            name='pipeline_param_1',
        ),
        migrations.RemoveField(
            model_name='userpipelineconfig',
            name='pipeline_param_2',
        ),
        migrations.RemoveField(
            model_name='userpipelineconfig',
            name='pipeline_param_3',
        ),
        migrations.AddField(
            model_name='userpipelineconfig',
            name='confidence_wrinkle',
            field=models.IntegerField(default=0.5),
        ),
    ]
