# Generated by Django 4.0.2 on 2023-09-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_remove_userpipelineconfig_pipeline_param_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpipelineconfig',
            name='confidence_wrinkle',
            field=models.FloatField(default=0.5),
        ),
    ]
